export class Especialidade {

    
   OBSTETRICIA: "OBSTETRICIA";
   MEDICINA_DA_FAMILIA =  "MEDICINA_DA_FAMILIA";
   GINECOLOGIA  =  "GINECOLOGIA";
   CLINICA_MEDICA : "CLINICA_MEDICA";
   PEDIATRIA : "PEDIATRIA";


}