export class Especialidade {

    CLINICA_MEDICA = "CLINICA_MEDICA";
    CARDIOLOGIA = "CARDIOLOGIA";
    NEUROLOGIA = "NEUROLOGIA";
    PSQUIATRIA = "PSQUIATRIA";
    ENDOCRINOLOGIA = "ENDOCRIONOLOGIA";
    ORTOPEDIA = "ORTOPEDIA";
    DERMATOLOGIA = "DERMATOLOGIA";
    OFTALMOLOGIA = "OFTALMOLOGIA";
    ANESTESIOLOGIA = "ANESTESIOLOGIA";
    GINECOLOGIA = "GINECOLOGIA";
    PEDIATRIA = "PEDIATRIA";
    RANDOMICO = "RANDOMICO";

}